### ISSUE TITLE
Can't find worker file

### ISSUE THREAD

**Issue by niklasravnsborg** [studio-lagier/next-wasm-workers#1]
Hey @tomlagier!

Thanks for your article and this repo. I tried to use it as a reference for a project where I try to load a web worker that is written in Typescript with Next 11 / Webpack 5. In my project I couldn't get Next.js to expose the worker file so I tried to download your repository. It turns out, I get the same error here:

<img width="1435" alt="Screenshot 2021-07-28 at 13 13 40" src="https://user-images.githubusercontent.com/6717303/127313719-23219f97-079f-421d-beaf-1ea47b622564.png">

I just added a console.log statement to `index.tsx`.

```
const workerUrl = new URL('../src/ts.worker.ts', import.meta.url);
console.log(workerUrl);
tsWorkerRef.current = new Worker(workerUrl);
```

When I manually navigate to http://localhost:3000/_next/94ab9802796300a474cd.ts, I also get the 404. I would assume, that you should get the same behavior. Do you have an idea on how to fix this?

**Comment by tomlagier** [comment]
Hmm.. I'll take a look now.

**Comment by tomlagier** [comment]
Interestingly, I'm not getting this behavior with either `next dev` or `next build && next start`. If you `next build`, what's the `.next` folder look like? Can you find the missing file there?

![image](https://user-images.githubusercontent.com/3165151/128644613-8f3e57fb-7172-44ff-8b2e-a672dbdfe070.png)

Here's the network requests after `next build && next start`: 
![image](https://user-images.githubusercontent.com/3165151/128644680-c06577cd-0b9c-40f0-bf8f-80545d363a2b.png)

I think it's gotta be an environment issue here - something bound to the port, some version mismatch, etc.

**Comment by niklasravnsborg** [comment]
Hey, it turns out, adding the `workerUrl` constant is causing the issue:

This works fine: 

```ts
tsWorkerRef.current = new Worker(new URL('../src/ts.worker.ts', import.meta.url));
```

This causes the error I experienced:

```ts
const workerUrl = new URL('../src/ts.worker.ts', import.meta.url);
console.log(workerUrl);
tsWorkerRef.current = new Worker(workerUrl);
```

I guess this is some kind of Webpack behavior and it can only bundle static webworker files when they can be analyzed in one statement.

Thank you for checking :)
